const ProjectsContent = [
    {
        lang: "TR",
        projects: [
            {
                title: "Crown Clothing - E-Ticaret",
                technologies: "React, Redux, Redux-Persist, Redux-Saga, Hooks, SCSS, Stripe, Firebase",
                imgs: ["https://i.ibb.co/6NY1yy5/crwn-checkout.png", "https://i.ibb.co/xqsTxhp/crwn-homepage.png", "https://i.ibb.co/WWTBqvr/crwn-shop-category.png", "https://i.ibb.co/MGh26c1/crwn-user-signup.png"],
                githubLink: "https://github.com/sumeyye-uzgor/CRWN-Clothing",
                liveLink: "https://clothing-crwon-live.herokuapp.com",
                isLive: true,
                id: 1,
            },
            {
                title: "Harmantepe Naturel - E-Ticaret",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, Paynet, Backend API",
                imgs: ["https://i.ibb.co/bN5z02C/harmantepe-checkout.png", "https://i.ibb.co/rxtYBYG/harmantepe-homepage.png", "https://i.ibb.co/7zDSzgm/harmantepe-shop-category.png", "https://i.ibb.co/zSCSx3d/harmantepe-user-signup.png"],
                githubLink: "https://github.com/sumeyye-uzgor/",
                liveLink: "https://harmantepenaturel.com",
                isLive: true,
                id: 2,
            },
            {
                title: "Movie UP - Basit Film Araştırma Motoru",
                technologies: "Nextjs, Redux, Redux-Persist, OMDB API",
                imgs: ["https://i.ibb.co/93JSkmY/movieup-homepage.png", "https://i.ibb.co/nQLtGrV/movieup-searchresult.png", "https://i.ibb.co/10r6k8b/movieup-favs.png", "https://i.ibb.co/YL1d0dr/movieup-details.png"],
                githubLink: "https://github.com/sumeyye-uzgor/movie-up",
                liveLink: "https://movieup-demo.herokuapp.com/",
                isLive: true,
                id: 3,
            },
            {
                title: "CatchMyPhoto - Canlı Fotoğraf Çekme Sitesi",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
                imgs: ["https://i.ibb.co/qFq28cq/catchmyphoto-1.png"],
                githubLink: "https://github.com/sumeyye-uzgor/catch-my-photo",
                liveLink: "https://catch-my-photo.herokuapp.com/",
                isLive: true,
                id: 4,
            },
            {
                title: "Quiz - Quiz Sitesi",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
                imgs: ["https://i.ibb.co/frCFYQS/QuizApp.png", "https://i.ibb.co/X4FD1fy/QuizApp3.png", "https://i.ibb.co/fvGbcrv/QuizApp2.png"],
                githubLink: "https://github.com/sumeyye-uzgor/VueQuiz",
                liveLink: "https://quizme-demo.netlify.app/",
                isLive: true,
                id: 5,
            },
            // {
            //     title: "PetShop - PetShop Sitesi",
            //     technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
            //     imgs: [],
            //     githubLink: "https://github.com/sumeyye-uzgor/catch-my-photo",
            //     liveLink: "",
            //     isLive: false,
            //     id: 6,
            // },
            {
                title: "DrumMachine - Sanal Davul",
                technologies: "React, Bootstrap, HTML Audio, Redux",
                imgs: ["https://i.ibb.co/FKbpXGw/drum-machine.png", "https://i.ibb.co/4YNqKYj/drum-machine2.png"],
                githubLink: "https://github.com/sumeyye-uzgor/drum-machine",
                liveLink: "https://virtual-drum.netlify.app/",
                isLive: true,
                id: 7,
            }
        ]
    },

    {
        lang: "EN",
        projects: [
            {
                title: "Crown Clothing - E-Commerce",
                technologies: "React, Redux, Redux-Persist, Redux-Saga, Hooks, SCSS, Stripe, Firebase",
                imgs: ["https://i.ibb.co/6NY1yy5/crwn-checkout.png", "https://i.ibb.co/xqsTxhp/crwn-homepage.png", "https://i.ibb.co/WWTBqvr/crwn-shop-category.png", "https://i.ibb.co/MGh26c1/crwn-user-signup.png"],
                githubLink: "https://github.com/sumeyye-uzgor/CRWN-Clothing",
                liveLink: "https://clothing-crwon-live.herokuapp.com",
                isLive: true,
                id: 1,
            },
            {
                title: "Harmantepe Naturel - E-Commerce",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, Paynet, Backend API",
                imgs: ["https://i.ibb.co/bN5z02C/harmantepe-checkout.png", "https://i.ibb.co/rxtYBYG/harmantepe-homepage.png", "https://i.ibb.co/7zDSzgm/harmantepe-shop-category.png", "https://i.ibb.co/zSCSx3d/harmantepe-user-signup.png"],
                githubLink: "https://github.com/sumeyye-uzgor",
                liveLink: "https://harmantepenaturel.com",
                isLive: true,
                id: 2,
            },
            {
                title: "Movie UP - Basic Movie Search Engine",
                technologies: "Nextjs, Redux, Redux-Persist, OMDB API",
                imgs: ["https://i.ibb.co/93JSkmY/movieup-homepage.png", "https://i.ibb.co/nQLtGrV/movieup-searchresult.png", "https://i.ibb.co/10r6k8b/movieup-favs.png", "https://i.ibb.co/YL1d0dr/movieup-details.png"],
                githubLink: "https://github.com/sumeyye-uzgor/movie-up",
                liveLink: "https://movieup-demo.herokuapp.com/",
                isLive: true,
                id: 3,
            },
            {
                title: "CatchMyPhoto - Live Phooto Shooter Website",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
                imgs: ["https://i.ibb.co/qFq28cq/catchmyphoto-1.png"],
                githubLink: "https://github.com/sumeyye-uzgor/catch-my-photo",
                liveLink: "https://catch-my-photo.herokuapp.com/",
                isLive: true,
                id: 4,
            },
            {
                title: "Quiz - Quiz Website",
                technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
                imgs: ["https://i.ibb.co/frCFYQS/QuizApp.png", "https://i.ibb.co/X4FD1fy/QuizApp3.png", "https://i.ibb.co/fvGbcrv/QuizApp2.png"],
                githubLink: "https://github.com/sumeyye-uzgor/VueQuiz",
                liveLink: "https://quizme-demo.netlify.app/",
                isLive: true,
                id: 5,
            },
            // {
            //     title: "PetShop - Basic Petshop Website",
            //     technologies: "Vue, Vuex, Vuex-Persistor, Vuetify, HTML Video, HTML Canvas",
            //     imgs: [],
            //     githubLink: "https://github.com/sumeyye-uzgor/catch-my-photo",
            //     liveLink: "https://catch-my-photo.herokuapp.com/",
            //     isLive: false,
            //     id: 6,
            // },
            {
                title: "DrumMachine - Virtual Drum",
                technologies: "React, Bootstrap, HTML Audio, Redux",
                imgs: ["https://i.ibb.co/FKbpXGw/drum-machine.png", "https://i.ibb.co/4YNqKYj/drum-machine2.png"],
                githubLink: "https://github.com/sumeyye-uzgor/drum-machine",
                liveLink: "https://virtual-drum.netlify.app/",
                isLive: true,
                id: 7,
            }
        ]
    }
]
export default ProjectsContent
